{ ... }:
{
  # Only config.yml is managed here. hosts.yml holds the auth token and stays
  # generated by `gh auth login`, outside of nix and outside of git.
  programs.gh = {
    enable = true;
    settings = {
      version = 1;
      git_protocol = "https";
      prompt = "enabled";
      aliases = {
        co = "pr checkout";
      };
    };
  };
}
